service: multiclouddeploymentblog

provider:
  name: azure
  region: North Europe
  runtime: nodejs10.x
  # prefix: "sample"  # prefix of generated resource name
  # subscriptionId: A356AC8C-E310-44F4-BF85-C7F29044AF99
  # stage: dev
  # type: premium  # premium azure functions

  environment: # these will be created as application settings
    MONGODB: 'mongodb+srv://masnad:Qwerty123456@cluster0-xwosk.gcp.mongodb.net/test?retryWrites=true&w=majority'


plugins: # look for additional plugins in the community plugins repo: https://github.com/serverless/plugins
  - serverless-azure-functions

# you can add packaging information here
package:
  # include:
  #   - include-me.js
  #   - include-me-dir/**
  exclude:
    # - exclude-me.js
    # - exclude-me-dir/**
    - local.settings.json
    - .vscode/**

functions:
  get:
    handler: src/handlers/hello.get
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous # can also be `function` or `admin`

  status:
    handler: src/handlers/hello.status
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous # can also be `function` or `admin`
  
  create:
    handler: src/handlers/hello.create
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          authLevel: anonymous # can also be `function` or `admin`