service: multiclouddeployment-sms

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: us-central1
  project: multiclouddeploymentgcp
 
  credentials: keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  send-sms:
    handler: http
    events:
      - http: path
